[functions.stripe-webhook]
verify_jwt = false

[functions.food-stripe-checkout]
verify_jwt = true

[functions.food-stripe-cancel]
verify_jwt = true

[functions.merchant-stripe-connect]
verify_jwt = true

[functions.merchant-stripe-refund]
verify_jwt = true
