-- WYNOS Finance Control Center v1 (core)
-- Additive finance/control layer for WYNOS Food, Merchant, Payments and future Rider.
-- Existing Food/Stripe/Campaign tables remain authoritative where already appropriate.
-- No historical order, payment mapping or settlement is deleted or recalculated.
-- Money/ledger calculations use integer satang (bigint).

create table if not exists public.food_finance_config_versions (
  id uuid primary key default gen_random_uuid(),
  version_no bigint generated by default as identity unique,
  effective_from timestamptz not null default now(),
  effective_to timestamptz,
  default_gp_bps integer not null default 1000,
  base_delivery_satang bigint not null default 2500,
  included_distance_meters integer not null default 2000,
  delivery_per_km_satang bigint not null default 700,
  minimum_delivery_satang bigint not null default 0,
  maximum_delivery_satang bigint,
  distance_rounding text not null default 'ceil_km',
  free_delivery_threshold_satang bigint,
  long_distance_threshold_meters integer,
  long_distance_surcharge_satang bigint not null default 0,
  peak_surcharge_satang bigint not null default 0,
  rain_surcharge_satang bigint not null default 0,
  rider_base_pay_satang bigint not null default 2500,
  rider_pay_per_km_satang bigint not null default 500,
  rider_min_earning_satang bigint not null default 0,
  rider_long_distance_bonus_satang bigint not null default 0,
  rider_peak_bonus_satang bigint not null default 0,
  rider_rain_bonus_satang bigint not null default 0,
  rider_platform_fee_bps integer not null default 0,
  rider_incentive_jobs integer,
  rider_incentive_bonus_satang bigint not null default 0,
  service_fee_mode text not null default 'fixed',
  service_fee_value bigint not null default 0,
  service_fee_min_satang bigint,
  service_fee_max_satang bigint,
  small_order_threshold_satang bigint,
  small_order_fee_satang bigint not null default 0,
  surge_fee_mode text not null default 'fixed',
  surge_fee_value bigint not null default 0,
  surge_fee_min_satang bigint,
  surge_fee_max_satang bigint,
  stripe_fee_bearer text not null default 'wynos',
  stripe_fee_merchant_share_bps integer not null default 0,
  tax_enabled boolean not null default false,
  vat_registered boolean not null default false,
  vat_bps integer not null default 700,
  created_by uuid references auth.users(id) on delete set null,
  reason text not null default 'Initial finance configuration',
  created_at timestamptz not null default now(),
  constraint food_finance_config_dates check (effective_to is null or effective_to > effective_from),
  constraint food_finance_config_gp check (default_gp_bps between 0 and 10000),
  constraint food_finance_config_nonnegative check (
    base_delivery_satang >= 0
    and included_distance_meters >= 0
    and delivery_per_km_satang >= 0
    and minimum_delivery_satang >= 0
    and (maximum_delivery_satang is null or maximum_delivery_satang >= minimum_delivery_satang)
    and long_distance_surcharge_satang >= 0
    and peak_surcharge_satang >= 0
    and rain_surcharge_satang >= 0
    and rider_base_pay_satang >= 0
    and rider_pay_per_km_satang >= 0
    and rider_min_earning_satang >= 0
    and rider_long_distance_bonus_satang >= 0
    and rider_peak_bonus_satang >= 0
    and rider_rain_bonus_satang >= 0
    and rider_incentive_bonus_satang >= 0
    and service_fee_value >= 0
    and small_order_fee_satang >= 0
    and surge_fee_value >= 0
  ),
  constraint food_finance_config_rounding check (distance_rounding in ('none','ceil_100m','ceil_500m','ceil_km')),
  constraint food_finance_config_fee_modes check (service_fee_mode in ('fixed','percent_bps') and surge_fee_mode in ('fixed','percent_bps')),
  constraint food_finance_config_bps check (
    rider_platform_fee_bps between 0 and 10000
    and stripe_fee_merchant_share_bps between 0 and 10000
    and vat_bps between 0 and 10000
  ),
  constraint food_finance_config_stripe_bearer check (stripe_fee_bearer in ('wynos','merchant','shared')),
  constraint food_finance_config_reason check (char_length(btrim(reason)) between 3 and 500)
);

create index if not exists food_finance_config_effective_idx
  on public.food_finance_config_versions(effective_from desc, effective_to);

alter table public.food_finance_config_versions enable row level security;
revoke all on table public.food_finance_config_versions from public, anon, authenticated;
grant select, insert, update on table public.food_finance_config_versions to service_role;

create table if not exists public.platform_feature_flags (
  key text primary key,
  enabled boolean not null,
  effective_from timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  reason text not null default 'Initial feature flag',
  updated_at timestamptz not null default now(),
  constraint platform_feature_flags_key check (key ~ '^[a-z][a-z0-9_]{2,80}$'),
  constraint platform_feature_flags_reason check (char_length(btrim(reason)) between 3 and 500)
);

alter table public.platform_feature_flags enable row level security;
revoke all on table public.platform_feature_flags from public, anon, authenticated;
grant select, insert, update on table public.platform_feature_flags to service_role;

insert into public.platform_feature_flags(key, enabled, reason) values
  ('promptpay_enabled', true, 'Production default: PromptPay only'),
  ('card_enabled', false, 'Production default: card disabled'),
  ('apple_pay_enabled', false, 'Production default: Apple Pay disabled'),
  ('google_pay_enabled', false, 'Production default: Google Pay disabled'),
  ('rider_enabled', false, 'Rider production rollout not QA-approved'),
  ('service_fee_enabled', false, 'Production default: service fee disabled'),
  ('small_order_fee_enabled', false, 'Production default: small-order fee disabled'),
  ('surge_pricing_enabled', false, 'Production default: surge pricing disabled'),
  ('peak_pricing_enabled', false, 'Production default: peak pricing disabled'),
  ('rain_surcharge_enabled', false, 'Production default: rain surcharge disabled'),
  ('long_distance_surcharge_enabled', false, 'Production default: long-distance surcharge disabled'),
  ('merchant_payout_enabled', false, 'Merchant payout engine staged until QA'),
  ('promotion_enabled', true, 'Existing promotion system remains enabled')
on conflict (key) do nothing;

create table if not exists public.food_merchant_gp_rules (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.food_stores(id) on delete cascade,
  rule_type text not null,
  gp_bps integer not null,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  active boolean not null default true,
  reason text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint food_merchant_gp_rules_type check (rule_type in ('custom','temporary')),
  constraint food_merchant_gp_rules_bps check (gp_bps between 0 and 10000),
  constraint food_merchant_gp_rules_dates check (ends_at is null or ends_at > starts_at),
  constraint food_merchant_gp_rules_reason check (char_length(btrim(reason)) between 3 and 500)
);

create index if not exists food_merchant_gp_rules_lookup_idx
  on public.food_merchant_gp_rules(store_id, active, rule_type, starts_at desc, ends_at);

alter table public.food_merchant_gp_rules enable row level security;
revoke all on table public.food_merchant_gp_rules from public, anon, authenticated;
grant select, insert, update on table public.food_merchant_gp_rules to service_role;

create table if not exists public.food_merchant_finance_controls (
  store_id uuid primary key references public.food_stores(id) on delete cascade,
  payments_enabled boolean,
  payout_suspended boolean not null default false,
  promotion_eligible boolean not null default true,
  delivery_override_enabled boolean not null default false,
  base_delivery_satang bigint,
  included_distance_meters integer,
  delivery_per_km_satang bigint,
  minimum_delivery_satang bigint,
  maximum_delivery_satang bigint,
  distance_rounding text,
  updated_by uuid references auth.users(id) on delete set null,
  reason text,
  updated_at timestamptz not null default now(),
  constraint food_merchant_finance_delivery_nonnegative check (
    (base_delivery_satang is null or base_delivery_satang >= 0)
    and (included_distance_meters is null or included_distance_meters >= 0)
    and (delivery_per_km_satang is null or delivery_per_km_satang >= 0)
    and (minimum_delivery_satang is null or minimum_delivery_satang >= 0)
    and (maximum_delivery_satang is null or maximum_delivery_satang >= 0)
  ),
  constraint food_merchant_finance_rounding check (
    distance_rounding is null or distance_rounding in ('none','ceil_100m','ceil_500m','ceil_km')
  )
);

alter table public.food_merchant_finance_controls enable row level security;
revoke all on table public.food_merchant_finance_controls from public, anon, authenticated;
grant select, insert, update on table public.food_merchant_finance_controls to service_role;

alter table public.food_service_areas add column if not exists province_code text;
update public.food_service_areas
set province_code = 'maha_sarakham'
where code = 'maha_sarakham' and province_code is null;

create table if not exists public.food_delivery_pricing_rules (
  id uuid primary key default gen_random_uuid(),
  scope_type text not null,
  scope_value text not null,
  priority integer not null default 100,
  active boolean not null default true,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  base_delivery_satang bigint,
  included_distance_meters integer,
  delivery_per_km_satang bigint,
  minimum_delivery_satang bigint,
  maximum_delivery_satang bigint,
  distance_rounding text,
  free_delivery_threshold_satang bigint,
  long_distance_threshold_meters integer,
  long_distance_surcharge_satang bigint,
  created_by uuid references auth.users(id) on delete set null,
  reason text not null,
  created_at timestamptz not null default now(),
  constraint food_delivery_pricing_scope check (scope_type in ('service_area','province')),
  constraint food_delivery_pricing_dates check (ends_at is null or ends_at > starts_at),
  constraint food_delivery_pricing_nonnegative check (
    (base_delivery_satang is null or base_delivery_satang >= 0)
    and (included_distance_meters is null or included_distance_meters >= 0)
    and (delivery_per_km_satang is null or delivery_per_km_satang >= 0)
    and (minimum_delivery_satang is null or minimum_delivery_satang >= 0)
    and (maximum_delivery_satang is null or maximum_delivery_satang >= 0)
    and (free_delivery_threshold_satang is null or free_delivery_threshold_satang >= 0)
    and (long_distance_threshold_meters is null or long_distance_threshold_meters >= 0)
    and (long_distance_surcharge_satang is null or long_distance_surcharge_satang >= 0)
  ),
  constraint food_delivery_pricing_rounding check (
    distance_rounding is null or distance_rounding in ('none','ceil_100m','ceil_500m','ceil_km')
  ),
  constraint food_delivery_pricing_reason check (char_length(btrim(reason)) between 3 and 500)
);

create index if not exists food_delivery_pricing_rules_lookup_idx
  on public.food_delivery_pricing_rules(scope_type, scope_value, active, priority desc, starts_at desc);

alter table public.food_delivery_pricing_rules enable row level security;
revoke all on table public.food_delivery_pricing_rules from public, anon, authenticated;
grant select, insert, update on table public.food_delivery_pricing_rules to service_role;

create table if not exists public.food_riders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references auth.users(id) on delete set null,
  status text not null default 'pending',
  active boolean not null default false,
  service_area_codes text[] not null default '{}',
  payout_suspended boolean not null default false,
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  suspended_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint food_riders_status check (status in ('pending','approved','suspended','rejected'))
);

create table if not exists public.food_rider_order_earnings (
  order_id uuid primary key references public.food_orders(id) on delete restrict,
  rider_id uuid references public.food_riders(id) on delete set null,
  config_version_id uuid references public.food_finance_config_versions(id) on delete restrict,
  base_pay_satang bigint not null default 0,
  distance_pay_satang bigint not null default 0,
  long_distance_bonus_satang bigint not null default 0,
  peak_bonus_satang bigint not null default 0,
  rain_bonus_satang bigint not null default 0,
  incentive_satang bigint not null default 0,
  adjustment_satang bigint not null default 0,
  platform_fee_satang bigint not null default 0,
  gross_earning_satang bigint not null default 0,
  payable_satang bigint not null default 0,
  paid_satang bigint not null default 0,
  payout_status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint food_rider_earnings_nonnegative check (
    base_pay_satang >= 0 and distance_pay_satang >= 0
    and long_distance_bonus_satang >= 0 and peak_bonus_satang >= 0
    and rain_bonus_satang >= 0 and incentive_satang >= 0
    and platform_fee_satang >= 0 and gross_earning_satang >= 0
    and payable_satang >= 0 and paid_satang >= 0
  ),
  constraint food_rider_payout_status check (payout_status in ('pending','held','processing','paid','failed'))
);

create table if not exists public.food_rider_adjustments (
  id uuid primary key default gen_random_uuid(),
  rider_id uuid not null references public.food_riders(id) on delete cascade,
  order_id uuid references public.food_orders(id) on delete set null,
  amount_satang bigint not null,
  reason text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint food_rider_adjustment_reason check (char_length(btrim(reason)) between 3 and 500)
);

create table if not exists public.food_rider_payouts (
  id uuid primary key default gen_random_uuid(),
  rider_id uuid not null references public.food_riders(id) on delete restrict,
  amount_satang bigint not null check (amount_satang > 0),
  status text not null default 'pending',
  reference text,
  period_start timestamptz,
  period_end timestamptz,
  paid_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint food_rider_payout_status_check check (status in ('pending','processing','paid','failed','cancelled'))
);

alter table public.food_riders enable row level security;
alter table public.food_rider_order_earnings enable row level security;
alter table public.food_rider_adjustments enable row level security;
alter table public.food_rider_payouts enable row level security;
revoke all on table public.food_riders, public.food_rider_order_earnings, public.food_rider_adjustments, public.food_rider_payouts
  from public, anon, authenticated;
grant select, insert, update on table public.food_riders, public.food_rider_order_earnings, public.food_rider_adjustments, public.food_rider_payouts
  to service_role;

alter table public.food_orders
  add column if not exists finance_config_version_id uuid references public.food_finance_config_versions(id) on delete restrict,
  add column if not exists finance_snapshot jsonb,
  add column if not exists subtotal_satang bigint,
  add column if not exists delivery_fee_satang bigint,
  add column if not exists service_fee_satang bigint,
  add column if not exists small_order_fee_satang bigint,
  add column if not exists surge_fee_satang bigint,
  add column if not exists discount_total_satang bigint,
  add column if not exists merchant_discount_satang bigint,
  add column if not exists platform_discount_satang bigint,
  add column if not exists gp_bps integer,
  add column if not exists gp_amount_satang bigint,
  add column if not exists stripe_fee_satang bigint,
  add column if not exists rider_earning_satang bigint,
  add column if not exists merchant_net_satang bigint,
  add column if not exists platform_revenue_satang bigint,
  add column if not exists customer_total_satang bigint,
  add column if not exists stripe_fee_bearer_snapshot text,
  add column if not exists stripe_fee_merchant_share_bps_snapshot integer,
  add column if not exists tax_enabled_snapshot boolean,
  add column if not exists vat_bps_snapshot integer;

alter table public.food_orders drop constraint if exists food_orders_finance_snapshot_nonnegative;
alter table public.food_orders add constraint food_orders_finance_snapshot_nonnegative check (
  (subtotal_satang is null or subtotal_satang >= 0)
  and (delivery_fee_satang is null or delivery_fee_satang >= 0)
  and (service_fee_satang is null or service_fee_satang >= 0)
  and (small_order_fee_satang is null or small_order_fee_satang >= 0)
  and (surge_fee_satang is null or surge_fee_satang >= 0)
  and (discount_total_satang is null or discount_total_satang >= 0)
  and (merchant_discount_satang is null or merchant_discount_satang >= 0)
  and (platform_discount_satang is null or platform_discount_satang >= 0)
  and (gp_bps is null or gp_bps between 0 and 10000)
  and (gp_amount_satang is null or gp_amount_satang >= 0)
  and (stripe_fee_satang is null or stripe_fee_satang >= 0)
  and (rider_earning_satang is null or rider_earning_satang >= 0)
  and (merchant_net_satang is null or merchant_net_satang >= 0)
  and (customer_total_satang is null or customer_total_satang >= 0)
);

alter table public.food_stripe_payments
  add column if not exists gross_amount_satang bigint,
  add column if not exists stripe_fee_satang bigint,
  add column if not exists platform_fee_satang bigint,
  add column if not exists merchant_net_satang bigint,
  add column if not exists stripe_fee_bearer text,
  add column if not exists stripe_fee_merchant_share_bps integer,
  add column if not exists balance_transaction_id text,
  add column if not exists fee_source text not null default 'pending';

alter table public.food_stripe_payments drop constraint if exists food_stripe_payments_finance_nonnegative;
alter table public.food_stripe_payments add constraint food_stripe_payments_finance_nonnegative check (
  (gross_amount_satang is null or gross_amount_satang >= 0)
  and (stripe_fee_satang is null or stripe_fee_satang >= 0)
  and (platform_fee_satang is null or platform_fee_satang >= 0)
  and (merchant_net_satang is null or merchant_net_satang >= 0)
  and (stripe_fee_merchant_share_bps is null or stripe_fee_merchant_share_bps between 0 and 10000)
  and fee_source in ('pending','stripe_actual','manual_adjustment')
);

alter table public.food_campaigns
  add column if not exists funding_type text not null default 'merchant_funded';

alter table public.food_campaigns drop constraint if exists food_campaigns_funding_type_check;
alter table public.food_campaigns add constraint food_campaigns_funding_type_check check (
  funding_type in ('merchant_funded','wynos_funded','shared','delivery_subsidy','platform_campaign','store_coupon')
);

alter table public.food_order_campaigns
  add column if not exists merchant_discount_cost_satang bigint,
  add column if not exists platform_discount_cost_satang bigint,
  add column if not exists delivery_subsidy_satang bigint,
  add column if not exists funding_type_snapshot text;

create table if not exists public.food_refunds (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.food_orders(id) on delete restrict,
  stripe_account_id text not null,
  stripe_refund_id text unique,
  amount_satang bigint not null check (amount_satang > 0),
  currency text not null default 'thb',
  responsibility text not null,
  restore_gp boolean not null default false,
  refund_delivery_fee boolean not null default false,
  stripe_refund_fee_satang bigint,
  reason text not null,
  status text not null default 'pending',
  requested_by uuid references auth.users(id) on delete set null,
  idempotency_key text not null unique,
  livemode boolean not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint food_refunds_responsibility check (responsibility in ('wynos','merchant','shared')),
  constraint food_refunds_status check (status in ('pending','succeeded','failed','cancelled')),
  constraint food_refunds_reason check (char_length(btrim(reason)) between 3 and 500)
);

alter table public.food_refunds enable row level security;
revoke all on table public.food_refunds from public, anon, authenticated;
grant select, insert, update on table public.food_refunds to service_role;

create table if not exists public.food_merchant_settlements (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.food_stores(id) on delete restrict,
  period_start timestamptz not null,
  period_end timestamptz not null,
  gross_sales_satang bigint not null default 0,
  discounts_satang bigint not null default 0,
  gp_satang bigint not null default 0,
  payment_fees_satang bigint not null default 0,
  refunds_satang bigint not null default 0,
  adjustments_satang bigint not null default 0,
  net_revenue_satang bigint not null default 0,
  paid_out_satang bigint not null default 0,
  pending_payout_satang bigint not null default 0,
  status text not null default 'draft',
  payout_reference text,
  idempotency_key text not null unique,
  payout_suspended_snapshot boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  constraint food_merchant_settlement_dates check (period_end > period_start),
  constraint food_merchant_settlement_status check (status in ('draft','approved','held','processing','paid','failed'))
);

create table if not exists public.food_merchant_settlement_items (
  settlement_id uuid not null references public.food_merchant_settlements(id) on delete restrict,
  order_id uuid not null references public.food_orders(id) on delete restrict,
  merchant_net_satang bigint not null,
  refund_satang bigint not null default 0,
  adjustment_satang bigint not null default 0,
  primary key(settlement_id, order_id),
  unique(order_id)
);

alter table public.food_merchant_settlements enable row level security;
alter table public.food_merchant_settlement_items enable row level security;
revoke all on table public.food_merchant_settlements, public.food_merchant_settlement_items
  from public, anon, authenticated;
grant select, insert, update on table public.food_merchant_settlements, public.food_merchant_settlement_items
  to service_role;

create or replace function internal.food_feature_enabled(p_key text, p_at timestamptz default now())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select f.enabled
    from public.platform_feature_flags f
    where f.key = p_key and f.effective_from <= p_at
    limit 1
  ), false);
$$;
revoke all on function internal.food_feature_enabled(text,timestamptz) from public, anon, authenticated;

create or replace function internal.food_active_finance_config_id(p_at timestamptz default now())
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select c.id
  from public.food_finance_config_versions c
  where c.effective_from <= p_at
    and (c.effective_to is null or c.effective_to > p_at)
  order by c.effective_from desc, c.version_no desc
  limit 1;
$$;
revoke all on function internal.food_active_finance_config_id(timestamptz) from public, anon, authenticated;

create or replace function internal.food_service_area_code(p_lat double precision, p_lng double precision)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select a.code
  from public.food_service_areas a
  where a.active
    and p_lat is not null and p_lng is not null
    and p_lat between a.min_lat and a.max_lat
    and p_lng between a.min_lng and a.max_lng
    and internal.food_point_in_polygon(p_lat, p_lng, a.lats, a.lngs)
  order by a.code
  limit 1;
$$;
revoke all on function internal.food_service_area_code(double precision,double precision) from public, anon, authenticated;

create or replace function internal.food_effective_gp_bps(p_store_id uuid, p_at timestamptz default now())
returns integer
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_gp integer;
  v_config uuid;
begin
  select r.gp_bps into v_gp
  from public.food_merchant_gp_rules r
  where r.store_id = p_store_id
    and r.active and r.rule_type = 'temporary'
    and r.starts_at <= p_at and (r.ends_at is null or r.ends_at > p_at)
  order by r.starts_at desc, r.created_at desc limit 1;
  if v_gp is not null then return v_gp; end if;

  select r.gp_bps into v_gp
  from public.food_merchant_gp_rules r
  where r.store_id = p_store_id
    and r.active and r.rule_type = 'custom'
    and r.starts_at <= p_at and (r.ends_at is null or r.ends_at > p_at)
  order by r.starts_at desc, r.created_at desc limit 1;
  if v_gp is not null then return v_gp; end if;

  v_config := internal.food_active_finance_config_id(p_at);
  select c.default_gp_bps into v_gp
  from public.food_finance_config_versions c where c.id = v_config;
  return coalesce(v_gp, 1000);
end;
$$;
revoke all on function internal.food_effective_gp_bps(uuid,timestamptz) from public, anon, authenticated;

create or replace function internal.food_round_distance_meters(p_meters integer, p_mode text)
returns integer
language sql
immutable
set search_path = ''
as $$
  select case p_mode
    when 'ceil_100m' then ((greatest(p_meters,0) + 99) / 100) * 100
    when 'ceil_500m' then ((greatest(p_meters,0) + 499) / 500) * 500
    when 'ceil_km' then ((greatest(p_meters,0) + 999) / 1000) * 1000
    else greatest(p_meters,0)
  end;
$$;
revoke all on function internal.food_round_distance_meters(integer,text) from public, anon, authenticated;

create or replace function internal.food_delivery_fee(
  p_store_id uuid,
  p_latitude double precision,
  p_longitude double precision
)
returns table(distance_km numeric, delivery_fee numeric)
language plpgsql
stable
set search_path = ''
as $$
declare
  v_store public.food_stores%rowtype;
  v_distance numeric;
  v_distance_m integer;
  v_developer boolean := exists (
    select 1 from public.developer_accounts d where d.user_id = (select auth.uid())
  );
  v_config public.food_finance_config_versions%rowtype;
  v_control public.food_merchant_finance_controls%rowtype;
  v_rule public.food_delivery_pricing_rules%rowtype;
  v_area text;
  v_province text;
  v_base bigint;
  v_included integer;
  v_per_km bigint;
  v_min bigint;
  v_max bigint;
  v_rounding text;
  v_long_threshold integer;
  v_long_fee bigint;
  v_rounded integer;
  v_fee bigint;
begin
  select * into v_store from public.food_stores where id = p_store_id;
  if not found then raise exception 'store is not accepting orders'; end if;

  if not v_developer and not internal.food_in_service_area(v_store.latitude, v_store.longitude) then
    raise exception 'store is outside the service area';
  end if;

  if v_store.latitude is null then
    return query select null::numeric, v_store.delivery_fee;
    return;
  end if;

  if p_latitude is null or p_longitude is null
     or p_latitude not between -90 and 90 or p_longitude not between -180 and 180 then
    raise exception 'delivery location required';
  end if;
  if not v_developer and not internal.food_in_service_area(p_latitude, p_longitude) then
    raise exception 'outside service area';
  end if;

  v_distance := internal.food_distance_km(v_store.latitude, v_store.longitude, p_latitude, p_longitude);
  if v_distance > v_store.delivery_radius_km then raise exception 'outside delivery area'; end if;
  v_distance_m := round(v_distance * 1000)::integer;

  select c.* into v_config
  from public.food_finance_config_versions c
  where c.id = internal.food_active_finance_config_id(now());

  if not found then
    return query select v_distance,
      (v_store.delivery_fee + ceil(greatest(v_distance - v_store.delivery_base_km, 0) * v_store.delivery_fee_per_km))::numeric;
    return;
  end if;

  v_base := v_config.base_delivery_satang;
  v_included := v_config.included_distance_meters;
  v_per_km := v_config.delivery_per_km_satang;
  v_min := v_config.minimum_delivery_satang;
  v_max := v_config.maximum_delivery_satang;
  v_rounding := v_config.distance_rounding;
  v_long_threshold := v_config.long_distance_threshold_meters;
  v_long_fee := v_config.long_distance_surcharge_satang;

  v_area := internal.food_service_area_code(p_latitude,p_longitude);
  select a.province_code into v_province
  from public.food_service_areas a where a.code = v_area;

  select r.* into v_rule
  from public.food_delivery_pricing_rules r
  where r.active
    and r.starts_at <= now()
    and (r.ends_at is null or r.ends_at > now())
    and (
      (r.scope_type='service_area' and r.scope_value=v_area)
      or (r.scope_type='province' and r.scope_value=v_province)
    )
  order by case when r.scope_type='service_area' then 2 else 1 end desc,
           r.priority desc, r.starts_at desc
  limit 1;

  if found then
    v_base := coalesce(v_rule.base_delivery_satang,v_base);
    v_included := coalesce(v_rule.included_distance_meters,v_included);
    v_per_km := coalesce(v_rule.delivery_per_km_satang,v_per_km);
    v_min := coalesce(v_rule.minimum_delivery_satang,v_min);
    v_max := coalesce(v_rule.maximum_delivery_satang,v_max);
    v_rounding := coalesce(v_rule.distance_rounding,v_rounding);
    v_long_threshold := coalesce(v_rule.long_distance_threshold_meters,v_long_threshold);
    v_long_fee := coalesce(v_rule.long_distance_surcharge_satang,v_long_fee);
  end if;

  select c.* into v_control from public.food_merchant_finance_controls c where c.store_id=p_store_id;
  if found and v_control.delivery_override_enabled then
    v_base := coalesce(v_control.base_delivery_satang,v_base);
    v_included := coalesce(v_control.included_distance_meters,v_included);
    v_per_km := coalesce(v_control.delivery_per_km_satang,v_per_km);
    v_min := coalesce(v_control.minimum_delivery_satang,v_min);
    v_max := coalesce(v_control.maximum_delivery_satang,v_max);
    v_rounding := coalesce(v_control.distance_rounding,v_rounding);
  end if;

  v_rounded := internal.food_round_distance_meters(v_distance_m,v_rounding);
  v_fee := v_base + ((greatest(v_rounded-v_included,0)::bigint * v_per_km + 999) / 1000);

  if internal.food_feature_enabled('long_distance_surcharge_enabled',now())
     and v_long_threshold is not null and v_distance_m > v_long_threshold then
    v_fee := v_fee + v_long_fee;
  end if;
  if internal.food_feature_enabled('peak_pricing_enabled',now()) then
    v_fee := v_fee + v_config.peak_surcharge_satang;
  end if;
  if internal.food_feature_enabled('rain_surcharge_enabled',now()) then
    v_fee := v_fee + v_config.rain_surcharge_satang;
  end if;

  v_fee := greatest(v_fee,coalesce(v_min,0));
  if v_max is not null then v_fee := least(v_fee,v_max); end if;
  return query select v_distance, round(v_fee::numeric / 100,2);
end;
$$;
revoke all on function internal.food_delivery_fee(uuid,double precision,double precision) from public, anon, authenticated;

create or replace function internal.food_calculate_financials(
  p_store_id uuid,
  p_subtotal_satang bigint,
  p_delivery_fee_satang bigint,
  p_campaign_discount_satang bigint default 0,
  p_delivery_discount_satang bigint default 0,
  p_distance_meters integer default null,
  p_at timestamptz default now(),
  p_campaign_id uuid default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_config public.food_finance_config_versions%rowtype;
  v_gp_bps integer;
  v_gp bigint;
  v_platform_share_bps integer := 0;
  v_merchant_discount bigint := 0;
  v_platform_discount bigint := 0;
  v_delivery bigint := greatest(coalesce(p_delivery_fee_satang,0),0);
  v_service bigint := 0;
  v_small bigint := 0;
  v_surge bigint := 0;
  v_discount bigint := greatest(coalesce(p_campaign_discount_satang,0),0) + greatest(coalesce(p_delivery_discount_satang,0),0);
  v_customer_total bigint;
  v_rider bigint := 0;
  v_rider_distance bigint := 0;
  v_rider_bonus bigint := 0;
  v_platform_revenue bigint;
  v_merchant_net bigint;
  v_store_control public.food_merchant_finance_controls%rowtype;
begin
  select c.* into v_config
  from public.food_finance_config_versions c
  where c.id = internal.food_active_finance_config_id(p_at);
  if not found then raise exception 'finance configuration unavailable'; end if;

  v_gp_bps := internal.food_effective_gp_bps(p_store_id,p_at);

  if p_campaign_id is not null then
    select least(10000,greatest(0,round(coalesce(c.platform_share_percent,0)*100)::integer))
      into v_platform_share_bps
    from public.food_campaigns c where c.id=p_campaign_id;
  end if;
  v_platform_share_bps := coalesce(v_platform_share_bps,0);
  v_platform_discount := (greatest(coalesce(p_campaign_discount_satang,0),0) * v_platform_share_bps + 5000) / 10000;
  v_merchant_discount := greatest(coalesce(p_campaign_discount_satang,0),0) - v_platform_discount;
  v_platform_discount := v_platform_discount + greatest(coalesce(p_delivery_discount_satang,0),0);

  if internal.food_feature_enabled('service_fee_enabled',p_at) then
    if v_config.service_fee_mode='percent_bps' then
      v_service := (greatest(p_subtotal_satang,0) * v_config.service_fee_value + 5000) / 10000;
    else
      v_service := v_config.service_fee_value;
    end if;
    if v_config.service_fee_min_satang is not null then v_service := greatest(v_service,v_config.service_fee_min_satang); end if;
    if v_config.service_fee_max_satang is not null then v_service := least(v_service,v_config.service_fee_max_satang); end if;
  end if;

  if internal.food_feature_enabled('small_order_fee_enabled',p_at)
     and v_config.small_order_threshold_satang is not null
     and p_subtotal_satang < v_config.small_order_threshold_satang then
    v_small := v_config.small_order_fee_satang;
  end if;

  if internal.food_feature_enabled('surge_pricing_enabled',p_at) then
    if v_config.surge_fee_mode='percent_bps' then
      v_surge := (v_delivery * v_config.surge_fee_value + 5000) / 10000;
    else
      v_surge := v_config.surge_fee_value;
    end if;
    if v_config.surge_fee_min_satang is not null then v_surge := greatest(v_surge,v_config.surge_fee_min_satang); end if;
    if v_config.surge_fee_max_satang is not null then v_surge := least(v_surge,v_config.surge_fee_max_satang); end if;
  end if;

  if v_config.free_delivery_threshold_satang is not null
     and p_subtotal_satang >= v_config.free_delivery_threshold_satang then
    v_delivery := 0;
  end if;

  v_gp := (greatest(p_subtotal_satang - v_merchant_discount,0) * v_gp_bps + 5000) / 10000;

  if internal.food_feature_enabled('rider_enabled',p_at) then
    v_rider_distance := ((greatest(coalesce(p_distance_meters,0),0)::bigint * v_config.rider_pay_per_km_satang + 999) / 1000);
    if internal.food_feature_enabled('long_distance_surcharge_enabled',p_at)
       and v_config.long_distance_threshold_meters is not null
       and coalesce(p_distance_meters,0) > v_config.long_distance_threshold_meters then
      v_rider_bonus := v_rider_bonus + v_config.rider_long_distance_bonus_satang;
    end if;
    if internal.food_feature_enabled('peak_pricing_enabled',p_at) then
      v_rider_bonus := v_rider_bonus + v_config.rider_peak_bonus_satang;
    end if;
    if internal.food_feature_enabled('rain_surcharge_enabled',p_at) then
      v_rider_bonus := v_rider_bonus + v_config.rider_rain_bonus_satang;
    end if;
    v_rider := greatest(
      v_config.rider_base_pay_satang + v_rider_distance + v_rider_bonus,
      v_config.rider_min_earning_satang
    );
  end if;

  v_customer_total := greatest(
    p_subtotal_satang - v_discount + v_delivery + v_service + v_small + v_surge, 0
  );
  v_merchant_net := greatest(p_subtotal_satang - v_merchant_discount - v_gp,0);
  v_platform_revenue := v_gp + v_service + v_surge - v_platform_discount;
  select * into v_store_control from public.food_merchant_finance_controls where store_id=p_store_id;

  return jsonb_build_object(
    'config_version_id',v_config.id,
    'subtotal_satang',greatest(p_subtotal_satang,0),
    'delivery_fee_satang',v_delivery,
    'service_fee_satang',v_service,
    'small_order_fee_satang',v_small,
    'surge_fee_satang',v_surge,
    'discount_total_satang',v_discount,
    'merchant_discount_satang',v_merchant_discount,
    'platform_discount_satang',v_platform_discount,
    'gp_bps',v_gp_bps,
    'gp_amount_satang',v_gp,
    'stripe_fee_satang',0,
    'stripe_fee_bearer',v_config.stripe_fee_bearer,
    'stripe_fee_merchant_share_bps',v_config.stripe_fee_merchant_share_bps,
    'rider_earning_satang',v_rider,
    'rider_base_pay_satang',case when internal.food_feature_enabled('rider_enabled',p_at) then v_config.rider_base_pay_satang else 0 end,
    'rider_distance_pay_satang',v_rider_distance,
    'rider_bonus_satang',v_rider_bonus,
    'merchant_net_satang',v_merchant_net,
    'platform_revenue_satang',v_platform_revenue,
    'customer_total_satang',v_customer_total,
    'tax_enabled',v_config.tax_enabled,
    'vat_registered',v_config.vat_registered,
    'vat_bps',v_config.vat_bps,
    'payout_suspended',coalesce(v_store_control.payout_suspended,false),
    'calculated_at',p_at
  );
end;
$$;
revoke all on function internal.food_calculate_financials(uuid,bigint,bigint,bigint,bigint,integer,timestamptz,uuid)
  from public, anon, authenticated;

create or replace function public.food_quote_order_financial(
  p_store_id uuid,
  p_items jsonb,
  p_latitude double precision default null,
  p_longitude double precision default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_quote jsonb;
  v_fin jsonb;
  v_subtotal bigint;
  v_delivery bigint;
  v_campaign bigint;
  v_delivery_discount bigint;
  v_distance_m integer;
begin
  v_quote := public.food_quote_order(p_store_id,p_items,p_latitude,p_longitude);
  v_subtotal := round(coalesce((v_quote->>'subtotal')::numeric,0)*100)::bigint;
  v_delivery := round(coalesce((v_quote->>'delivery_fee')::numeric,0)*100)::bigint;
  v_campaign := round(coalesce((v_quote->>'campaign_discount')::numeric,0)*100)::bigint;
  v_delivery_discount := round(coalesce((v_quote->>'delivery_discount')::numeric,0)*100)::bigint;
  v_distance_m := case when v_quote->>'delivery_distance_km' is null then null
    else round((v_quote->>'delivery_distance_km')::numeric*1000)::integer end;

  v_fin := internal.food_calculate_financials(
    p_store_id,v_subtotal,v_delivery,v_campaign,v_delivery_discount,v_distance_m,now(),
    nullif(v_quote->>'campaign_id','')::uuid
  );

  return v_quote || jsonb_build_object(
    'delivery_fee',round(((v_fin->>'delivery_fee_satang')::bigint)::numeric/100,2),
    'service_fee',round(((v_fin->>'service_fee_satang')::bigint)::numeric/100,2),
    'small_order_fee',round(((v_fin->>'small_order_fee_satang')::bigint)::numeric/100,2),
    'surge_fee',round(((v_fin->>'surge_fee_satang')::bigint)::numeric/100,2),
    'total',round(((v_fin->>'customer_total_satang')::bigint)::numeric/100,2),
    'financials',v_fin
  );
end;
$$;
revoke all on function public.food_quote_order_financial(uuid,jsonb,double precision,double precision) from public, anon;
grant execute on function public.food_quote_order_financial(uuid,jsonb,double precision,double precision) to authenticated;

create or replace function internal.food_order_finance_snapshot()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_fin jsonb;
  v_distance_m integer;
begin
  if new.finance_snapshot is not null then return new; end if;
  v_distance_m := case when new.delivery_distance_km is null then null
    else round(new.delivery_distance_km*1000)::integer end;

  v_fin := internal.food_calculate_financials(
    new.store_id,
    round(new.subtotal*100)::bigint,
    round(coalesce(new.delivery_fee,0)*100)::bigint,
    round(coalesce(new.campaign_discount,0)*100)::bigint,
    round(coalesce(new.delivery_discount,0)*100)::bigint,
    v_distance_m,
    coalesce(new.created_at,now()),
    new.campaign_id
  );

  new.finance_config_version_id := (v_fin->>'config_version_id')::uuid;
  new.subtotal_satang := (v_fin->>'subtotal_satang')::bigint;
  new.delivery_fee_satang := (v_fin->>'delivery_fee_satang')::bigint;
  new.service_fee_satang := (v_fin->>'service_fee_satang')::bigint;
  new.small_order_fee_satang := (v_fin->>'small_order_fee_satang')::bigint;
  new.surge_fee_satang := (v_fin->>'surge_fee_satang')::bigint;
  new.discount_total_satang := (v_fin->>'discount_total_satang')::bigint;
  new.merchant_discount_satang := (v_fin->>'merchant_discount_satang')::bigint;
  new.platform_discount_satang := (v_fin->>'platform_discount_satang')::bigint;
  new.gp_bps := (v_fin->>'gp_bps')::integer;
  new.gp_amount_satang := (v_fin->>'gp_amount_satang')::bigint;
  new.stripe_fee_satang := 0;
  new.rider_earning_satang := (v_fin->>'rider_earning_satang')::bigint;
  new.merchant_net_satang := (v_fin->>'merchant_net_satang')::bigint;
  new.platform_revenue_satang := (v_fin->>'platform_revenue_satang')::bigint;
  new.customer_total_satang := (v_fin->>'customer_total_satang')::bigint;
  new.stripe_fee_bearer_snapshot := v_fin->>'stripe_fee_bearer';
  new.stripe_fee_merchant_share_bps_snapshot := (v_fin->>'stripe_fee_merchant_share_bps')::integer;
  new.tax_enabled_snapshot := (v_fin->>'tax_enabled')::boolean;
  new.vat_bps_snapshot := (v_fin->>'vat_bps')::integer;
  new.finance_snapshot := v_fin;
  new.delivery_fee := round(new.delivery_fee_satang::numeric/100,2);
  new.total := round(new.customer_total_satang::numeric/100,2);
  return new;
end;
$$;
revoke all on function internal.food_order_finance_snapshot() from public, anon, authenticated;

drop trigger if exists food_orders_finance_snapshot on public.food_orders;
create trigger food_orders_finance_snapshot
before insert on public.food_orders
for each row execute function internal.food_order_finance_snapshot();

create or replace function internal.food_order_finance_guard()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if current_user in ('authenticated','anon') and (
    new.finance_config_version_id is distinct from old.finance_config_version_id
    or new.finance_snapshot is distinct from old.finance_snapshot
    or new.subtotal_satang is distinct from old.subtotal_satang
    or new.delivery_fee_satang is distinct from old.delivery_fee_satang
    or new.service_fee_satang is distinct from old.service_fee_satang
    or new.small_order_fee_satang is distinct from old.small_order_fee_satang
    or new.surge_fee_satang is distinct from old.surge_fee_satang
    or new.discount_total_satang is distinct from old.discount_total_satang
    or new.merchant_discount_satang is distinct from old.merchant_discount_satang
    or new.platform_discount_satang is distinct from old.platform_discount_satang
    or new.gp_bps is distinct from old.gp_bps
    or new.gp_amount_satang is distinct from old.gp_amount_satang
    or new.stripe_fee_bearer_snapshot is distinct from old.stripe_fee_bearer_snapshot
    or new.stripe_fee_merchant_share_bps_snapshot is distinct from old.stripe_fee_merchant_share_bps_snapshot
    or new.tax_enabled_snapshot is distinct from old.tax_enabled_snapshot
    or new.vat_bps_snapshot is distinct from old.vat_bps_snapshot
  ) then
    raise exception 'order financial snapshot is immutable';
  end if;
  return new;
end;
$$;
revoke all on function internal.food_order_finance_guard() from public, anon, authenticated;

drop trigger if exists food_orders_finance_guard on public.food_orders;
create trigger food_orders_finance_guard
before update on public.food_orders
for each row execute function internal.food_order_finance_guard();

create or replace function internal.food_order_campaign_finance_snapshot()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_share_bps integer := 0;
  v_campaign_funding text := 'merchant_funded';
  v_campaign_satang bigint;
  v_delivery_satang bigint;
begin
  if new.campaign_id is not null then
    select least(10000,greatest(0,round(coalesce(c.platform_share_percent,0)*100)::integer)),
           c.funding_type
    into v_share_bps,v_campaign_funding
    from public.food_campaigns c where c.id=new.campaign_id;
  end if;
  v_campaign_satang := round(coalesce(new.campaign_discount,0)*100)::bigint;
  v_delivery_satang := round(coalesce(new.delivery_discount,0)*100)::bigint;
  new.platform_discount_cost_satang := (v_campaign_satang * coalesce(v_share_bps,0) + 5000) / 10000 + v_delivery_satang;
  new.merchant_discount_cost_satang := v_campaign_satang - ((v_campaign_satang * coalesce(v_share_bps,0) + 5000) / 10000);
  new.delivery_subsidy_satang := v_delivery_satang;
  new.funding_type_snapshot := coalesce(v_campaign_funding,'merchant_funded');
  return new;
end;
$$;
revoke all on function internal.food_order_campaign_finance_snapshot() from public, anon, authenticated;

drop trigger if exists food_order_campaigns_finance_snapshot on public.food_order_campaigns;
create trigger food_order_campaigns_finance_snapshot
before insert on public.food_order_campaigns
for each row execute function internal.food_order_campaign_finance_snapshot();

create or replace function public.food_payment_configuration()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  return jsonb_build_object(
    'promptpay_enabled',internal.food_feature_enabled('promptpay_enabled',now()),
    'card_enabled',internal.food_feature_enabled('card_enabled',now()),
    'apple_pay_enabled',internal.food_feature_enabled('apple_pay_enabled',now()),
    'google_pay_enabled',internal.food_feature_enabled('google_pay_enabled',now())
  );
end;
$$;
revoke all on function public.food_payment_configuration() from public, anon;
grant execute on function public.food_payment_configuration() to authenticated;

create or replace function public.food_record_stripe_actual_fee(
  p_order_id uuid,
  p_stripe_account_id text,
  p_balance_transaction_id text,
  p_stripe_fee_satang bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_payment public.food_stripe_payments%rowtype;
  v_order public.food_orders%rowtype;
  v_merchant_fee bigint := 0;
  v_platform_fee bigint := 0;
  v_share integer;
begin
  if p_stripe_fee_satang is null or p_stripe_fee_satang < 0 then raise exception 'invalid Stripe fee'; end if;

  select * into v_payment from public.food_stripe_payments where order_id=p_order_id for update;
  if not found or v_payment.stripe_account_id is distinct from p_stripe_account_id then
    raise exception 'original payment mapping required';
  end if;
  select * into v_order from public.food_orders where id=p_order_id for update;
  if not found then raise exception 'order not found'; end if;

  v_share := coalesce(v_order.stripe_fee_merchant_share_bps_snapshot,0);
  if v_order.stripe_fee_bearer_snapshot='merchant' then
    v_merchant_fee := p_stripe_fee_satang;
  elsif v_order.stripe_fee_bearer_snapshot='shared' then
    v_merchant_fee := (p_stripe_fee_satang * v_share + 5000) / 10000;
  end if;
  v_platform_fee := p_stripe_fee_satang - v_merchant_fee;

  update public.food_stripe_payments
  set gross_amount_satang=coalesce(gross_amount_satang,amount_satang),
      stripe_fee_satang=p_stripe_fee_satang,
      platform_fee_satang=v_platform_fee,
      merchant_net_satang=greatest(coalesce(v_order.merchant_net_satang,0)-v_merchant_fee,0),
      stripe_fee_bearer=v_order.stripe_fee_bearer_snapshot,
      stripe_fee_merchant_share_bps=v_share,
      balance_transaction_id=p_balance_transaction_id,
      fee_source='stripe_actual',
      updated_at=now()
  where order_id=p_order_id;

  update public.food_orders
  set stripe_fee_satang=p_stripe_fee_satang,
      merchant_net_satang=greatest(coalesce(merchant_net_satang,0)-v_merchant_fee,0),
      platform_revenue_satang=coalesce(platform_revenue_satang,0)-v_platform_fee
  where id=p_order_id;
end;
$$;
revoke all on function public.food_record_stripe_actual_fee(uuid,text,text,bigint) from public, anon, authenticated;
grant execute on function public.food_record_stripe_actual_fee(uuid,text,text,bigint) to service_role;
