-- WYNOS Maps reverse-place + public geocoder rate-limit v1
-- Reverse pin labels should prefer WYNOS-owned Places before any external geocoder.

create or replace function public.wynos_reverse_place(
  p_latitude double precision,
  p_longitude double precision,
  p_max_distance_km double precision default 0.12
)
returns table (
  place_id text,
  name text,
  address text,
  latitude double precision,
  longitude double precision,
  category text,
  verification_status text,
  merchant_store_id uuid,
  store_slug text,
  is_open boolean,
  delivery_radius_km numeric,
  distance_km numeric
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_developer boolean := coalesce(public.is_developer_account(), false);
  v_radius double precision := least(greatest(coalesce(p_max_distance_km, 0.12), 0.02), 0.50);
begin
  if p_latitude not between -90 and 90 or p_longitude not between -180 and 180 then
    raise exception 'invalid location';
  end if;

  return query
  select
    p.id,
    coalesce(nullif(p.name_th, ''), nullif(p.name_en, ''), 'สถานที่')::text,
    p.address,
    p.latitude,
    p.longitude,
    p.category,
    p.verification_status,
    s.id,
    s.slug,
    s.is_open,
    s.delivery_radius_km,
    internal.food_distance_km(p_latitude, p_longitude, p.latitude, p.longitude)
  from public.wynos_places p
  left join public.food_store_places fsp
    on fsp.id = p.food_store_place_id
  left join public.food_stores s
    on s.id = coalesce(p.merchant_store_id, fsp.store_id)
  where
    (
      p.is_active
      or (
        v_developer
        and s.id is not null
        and s.admin_suspended_at is null
      )
    )
    and internal.food_distance_km(p_latitude, p_longitude, p.latitude, p.longitude) <= v_radius
  order by
    internal.food_distance_km(p_latitude, p_longitude, p.latitude, p.longitude),
    (p.verification_status = 'wynos_verified') desc,
    (p.verification_status = 'merchant_verified') desc,
    case
      when p.category = 'building' then 0
      when p.category = 'restaurant' then 1
      when p.category = 'pickup_point' then 2
      else 3
    end,
    p.name_th
  limit 1;
end;
$$;

revoke all on function public.wynos_reverse_place(double precision,double precision,double precision)
from public;
grant execute on function public.wynos_reverse_place(double precision,double precision,double precision)
to anon, authenticated;

create table if not exists internal.wynos_maps_geocode_requests (
  id bigint generated by default as identity primary key,
  client_key text not null,
  requested_at timestamptz not null default now()
);

create index if not exists wynos_maps_geocode_requests_client_time_idx
on internal.wynos_maps_geocode_requests(client_key, requested_at desc);

create or replace function public.reserve_wynos_maps_geocode_request(
  p_client_key text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_key text := left(btrim(coalesce(p_client_key, '')), 128);
  v_count integer;
begin
  if v_key = '' then
    return false;
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_key, 0));

  delete from internal.wynos_maps_geocode_requests
  where requested_at < now() - interval '10 minutes';

  select count(*) into v_count
  from internal.wynos_maps_geocode_requests
  where client_key = v_key
    and requested_at >= now() - interval '1 minute';

  if v_count >= 30 then
    return false;
  end if;

  insert into internal.wynos_maps_geocode_requests(client_key)
  values (v_key);

  return true;
end;
$$;

revoke all on function public.reserve_wynos_maps_geocode_request(text)
from public, anon, authenticated;
grant execute on function public.reserve_wynos_maps_geocode_request(text)
to service_role;
