import type { Metadata, Viewport } from "next";
import "./globals.css";
import "./phase2.css";
import "./phase2-polish.css";
import "./phase3.css";
import "./parity.css";
import "./parity-auth-email.css";
import "./parity-final.css";
import "./parity-completion.css";
import "./parity-closure.css";
import "./post-detail-parity.css";
import "./parity-audit.css";
import "./profile-follow-audit.css";
import "./club-audit.css";
import "./club-detail-audit.css";
import "./profile-golden-final.css";
import "./club-detail-golden.css";
import "./golden-drop-card.css";
import "./club-post-card-web.css";
import "./founder-parity-lock.css";
import "./system-parity-lock.css";
import "./system-parity-final.css";
import "./interaction-parity-final.css";
import "./pixel-parity-final.css";
import "./pixel-parity-audit-closure.css";
import "./bottom-nav.css";
import "./home.css";
import "./design-system.css";
import "./auth-reference.css";
import "./content-reference.css";
import "./profile-reference.css";
import "./club-reference.css";
import "./chat-reference.css";
import "./threads-action-row.css";
import "./profile-home-feed.css";
export const metadata:Metadata={title:"WYNOS",description:"WYNOS social web"};
export const viewport:Viewport={width:"device-width",initialScale:1,viewportFit:"cover",themeColor:"#ffffff"};
export default function RootLayout({children}:Readonly<{children:React.ReactNode}>){return <html lang="th"><body>{children}</body></html>}
