import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata, Viewport } from "next";
import { preconnect } from "react-dom";
import { AppBottomNavHost } from "@/components/app-bottom-nav-runtime";
import { AppNavigationRuntime } from "@/components/app-navigation-runtime";
import { InstallPromptBanner } from "@/components/install-prompt-banner";
import { QueryProvider } from "@/components/query-provider";
import { SwipeBackGesture } from "@/components/swipe-back-gesture";
import { PageTransition } from "@/components/ui/page-transition";
import "./globals.css";
import "./phase2.css";
import "./phase3.css";
import "./parity.css";
import "./parity-auth-email.css";
import "./parity-final.css";
import "./parity-completion.css";
import "./parity-closure.css";
import "./post-detail-parity.css";
import "./parity-audit.css";
import "./profile-follow-audit.css";
import "./club-audit.css";
import "./profile-golden-final.css";
import "./club-detail-golden.css";
import "./golden-drop-card.css";
import "./founder-parity-lock.css";
import "./system-parity-lock.css";
import "./system-parity-final.css";
import "./interaction-parity-final.css";
import "./pixel-parity-final.css";
import "./pixel-parity-audit-closure.css";
import "./bottom-nav.css";
import "./home.css";
import "./design-system.css";
import "./auth-reference.css";
import "./content-reference.css";
import "./profile-reference.css";
import "./club-reference.css";
import "./chat-reference.css";
import "./threads-action-row.css";
import "./profile-home-feed.css";
import "./notifications-clean.css";
import "./chat-notes.css";
import "./conversation-modern.css";
import "./skeleton.css";
import "./install-prompt.css";
// WYN-181: static iOS launch images (public/splash/*.png, generated by
// web/__gen_splash.mjs from the transparent wynos_logo_mark.png — dark
// variants use a negated white version, since the mark is black ink and
// would otherwise vanish on a black splash). One entry per current iPhone/
// iPad screen size x light/dark; portrait only (landscape PWA launch is
// vanishingly rare and not worth doubling the asset count for).
const APPLE_STARTUP_IMAGES: { url: string; media: string }[] = [
    { url: "/splash/iphone-16-pro-max-portrait-light.png", media: "screen and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/iphone-16-pro-max-portrait-dark.png", media: "screen and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/iphone-16-pro-portrait-light.png", media: "screen and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/iphone-16-pro-portrait-dark.png", media: "screen and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/iphone-15-pro-max-14-pro-max-portrait-light.png", media: "screen and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/iphone-15-pro-max-14-pro-max-portrait-dark.png", media: "screen and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/iphone-15-pro-14-pro-portrait-light.png", media: "screen and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/iphone-15-pro-14-pro-portrait-dark.png", media: "screen and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/iphone-15-plus-14-plus-13-pro-max-12-pro-max-portrait-light.png", media: "screen and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/iphone-15-plus-14-plus-13-pro-max-12-pro-max-portrait-dark.png", media: "screen and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/iphone-15-14-13-13-pro-12-12-pro-portrait-light.png", media: "screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/iphone-15-14-13-13-pro-12-12-pro-portrait-dark.png", media: "screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/iphone-13-mini-12-mini-11-pro-xs-x-portrait-light.png", media: "screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/iphone-13-mini-12-mini-11-pro-xs-x-portrait-dark.png", media: "screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/iphone-11-pro-max-xs-max-portrait-light.png", media: "screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/iphone-11-pro-max-xs-max-portrait-dark.png", media: "screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/iphone-11-xr-portrait-light.png", media: "screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/iphone-11-xr-portrait-dark.png", media: "screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/iphone-8-plus-7-plus-6s-plus-portrait-light.png", media: "screen and (device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/iphone-8-plus-7-plus-6s-plus-portrait-dark.png", media: "screen and (device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/iphone-8-7-6s-se3-se2-portrait-light.png", media: "screen and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/iphone-8-7-6s-se3-se2-portrait-dark.png", media: "screen and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/iphone-se1-5s-portrait-light.png", media: "screen and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/iphone-se1-5s-portrait-dark.png", media: "screen and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/ipad-pro-12-9-portrait-light.png", media: "screen and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/ipad-pro-12-9-portrait-dark.png", media: "screen and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/ipad-pro-11-ipad-air-10-9-portrait-light.png", media: "screen and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/ipad-pro-11-ipad-air-10-9-portrait-dark.png", media: "screen and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/ipad-10-2-portrait-light.png", media: "screen and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/ipad-10-2-portrait-dark.png", media: "screen and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)" },
    { url: "/splash/ipad-mini-8-3-portrait-light.png", media: "screen and (device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)" },
    { url: "/splash/ipad-mini-8-3-portrait-dark.png", media: "screen and (device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)" },
];
// This Next.js version's `appleWebApp` metadata only emits the generic
// `mobile-web-app-capable` tag (see node_modules/next/dist/docs/01-app/
// 03-api-reference/04-functions/generate-metadata.md, "appleWebApp") and
// drops `apple-mobile-web-app-capable`, which iOS Safari actually needs to
// launch a home-screen icon in standalone mode instead of inside Safari's
// own browser chrome. Added back explicitly via `other`. `startupImage`,
// unlike `capable`, IS emitted correctly by this version (verified against
// node_modules/next/dist/lib/metadata/metadata.js) — no workaround needed.
export const metadata:Metadata={title:"WYNOS",description:"WYNOS social web",appleWebApp:{capable:true,statusBarStyle:"default",title:"WYNOS",startupImage:APPLE_STARTUP_IMAGES},other:{"apple-mobile-web-app-capable":"yes"}};
// maximumScale/userScalable: 1 disables pinch-zoom. Native apps (and the
// Flutter build this web app mirrors) never let a user pinch-zoom the UI —
// only a standalone-launched web app, still carrying a plain browser
// viewport, does. Without this it's the one thing that gives away "this is
// a website" even from the home-screen icon.
export const viewport:Viewport={width:"device-width",initialScale:1,maximumScale:1,userScalable:false,viewportFit:"cover",themeColor:[{media:"(prefers-color-scheme: light)",color:"#ffffff"},{media:"(prefers-color-scheme: dark)",color:"#000000"}]};
// Every route mounts DeveloperRouteGate on first paint, which immediately
// calls Supabase auth.getSession() — a cross-origin request that otherwise
// pays DNS + TCP + TLS from a cold start. Warming that connection while the
// HTML/JS is still streaming shaves that handshake off the critical path.
const supabaseOrigin = (() => {
  try {
    return process.env.NEXT_PUBLIC_SUPABASE_URL ? new URL(process.env.NEXT_PUBLIC_SUPABASE_URL).origin : null;
  } catch {
    return null;
  }
})();

export default function RootLayout({children}:Readonly<{children:React.ReactNode}>){
  if (supabaseOrigin) preconnect(supabaseOrigin, { crossOrigin: "anonymous" });
  return <html lang="th"><body><QueryProvider><AppNavigationRuntime /><SwipeBackGesture /><PageTransition>{children}</PageTransition><AppBottomNavHost /><InstallPromptBanner /></QueryProvider><Analytics /><SpeedInsights /></body></html>;
}
