"use client";

import type { MouseEvent, ReactNode } from "react";
import { Avatar } from "@/components/ui/avatar";
import { WynosIcon } from "@/components/ui/wynos-icon";

export type PostCardProps={authorName:string;timeLabel:string;text?:string;avatarSrc?:string|null;avatarFallback?:string;media?:ReactNode;liked?:boolean;likeCount?:number|string;commentCount?:number|string;repostCount?:number|string;onLike?:()=>void;onComment?:()=>void;onRepost?:()=>void;onOpen?:()=>void;layout?:"card"|"feed";className?:string};
function actionText(label:string,count?:number|string){return count===undefined||count===""?label:`${label} ${count}`}
function stopAndRun(event:MouseEvent<HTMLButtonElement>,action?:()=>void){event.stopPropagation();action?.()}
export function PostCard({authorName,timeLabel,text,avatarSrc,avatarFallback,media,liked=false,likeCount,commentCount,repostCount,onLike,onComment,onRepost,onOpen,layout="card",className}:PostCardProps){
if(layout==="feed")return <article className={["wyn-post-card--feed","post",className??""].filter(Boolean).join(" ")} onClick={onOpen}><Avatar alt={`รูปโปรไฟล์ของ ${authorName}`} as="div" className="avatar" fallback={avatarFallback} size={36} src={avatarSrc} variant="person"/><div className="post-body"><div className="post-meta"><span className="name">{authorName}</span><span className="time"> {timeLabel}</span></div>{text?<p className="post-text">{text}</p>:null}{media?<div className="wyn-post-card__media">{media}</div>:null}<div className="post-actions" aria-label="การทำงานกับโพสต์"><button aria-label={liked?"ยกเลิกถูกใจ":"ถูกใจ"} aria-pressed={liked} className={`action${liked?" liked":""}`} onClick={(event)=>stopAndRun(event,onLike)} type="button"><WynosIcon name="like" size={18}/>{likeCount}</button><button aria-label="แสดงความคิดเห็น" className="action" onClick={(event)=>stopAndRun(event,onComment)} type="button"><WynosIcon name="comment" size={18}/>{commentCount}</button><button aria-label="รีโพสต์" className="action" onClick={(event)=>stopAndRun(event,onRepost)} type="button"><WynosIcon name="repost" size={18}/>{repostCount}</button></div></div></article>;
return <article className={["wyn-post-card",className??""].filter(Boolean).join(" ")}><header className="wyn-post-card__header"><Avatar alt={`รูปโปรไฟล์ของ ${authorName}`} fallback={avatarFallback??authorName} size={42} src={avatarSrc} variant="person"/><div className="wyn-post-card__meta"><span className="wyn-post-card__author">{authorName}</span><time className="wyn-post-card__time">{timeLabel}</time></div></header>{text?<p className="wyn-post-card__text">{text}</p>:null}{media?<div className="wyn-post-card__media">{media}</div>:null}<div className="wyn-post-card__actions" aria-label="การทำงานกับโพสต์"><button aria-label={liked?"ยกเลิกถูกใจ":"ถูกใจ"} aria-pressed={liked} className={`wyn-post-action${liked?" wyn-post-action--liked":""}`} onClick={onLike} type="button"><WynosIcon name="like" size={19}/><span>{actionText("ถูกใจ",likeCount)}</span></button><button aria-label="แสดงความคิดเห็น" className="wyn-post-action" onClick={onComment} type="button"><WynosIcon name="comment" size={19}/><span>{actionText("คอมเมนต์",commentCount)}</span></button><button aria-label="รีโพสต์" className="wyn-post-action" onClick={onRepost} type="button"><WynosIcon name="repost" size={19}/><span>{actionText("รีโพสต์",repostCount)}</span></button></div></article>}
